server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking
    username: root
    password: password

  application:
    name: booking-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
