spring:
  application:
    name: trasaction-service
    greeting: "Hello from Transaction Server on startup!"

server:
  port: 8084


kafka:
  topic:
    name: transaction-created
    group-id: transaction-service
  