spring:
  port: 8081
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/expense-tracker-microservice
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
