server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

custom:
  greeting: "Hello from Config Server on startup!"

