spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistic_management_system
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
