spring:
  application:
    name: email_service

  mail:
    host: smtp.gmail.com
    port: 587
    username: i.sahil8968627582@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


resilience4j.retry:
  instances:
    emailServiceRetry:
      max-attempts: 5
      wait-duration: 2s
      retry-exceptions:
        - org.springframework.mail.MailException
      ignore-exceptions:
        - java.lang.IllegalArgumentException

            
            
            
            
